name: Format

on:
  push:
    branches: [ '**' ]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Format code
        uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--aosp --replace"
          commitMessage: Formatting (auto)
          githubToken: ${{ secrets.GITHUB_TOKEN }}
